apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cicd-application
  namespace: argocd
spec:
  project: default
  source:
  - chart: web-app
    repoURL: git@github.com:mohamedalaaelsafy/ArgoCD-Helm-Project.git
    targetRevision: 0.1.0
    helm:
      releaseName: web-app
    valueFiles:
    - charts/web-app/values.yaml
  - chart: jenkins
    repoURL: git@github.com:mohamedalaaelsafy/ArgoCD-Helm-Project.git
    targetRevision: 0.1.0
    helm:
      releaseName: jenkins
    valueFiles:
    - charts/jenkins/values.yaml
  # syncPolicy:
  #   automated:
  #     prune: true 
  #     selfHeal: true 
  #     allowEmpty: false 
  destination:
    server: https://kubernetes.default.svc
    # namespace: cicd


