apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cicd-application
  namespace: argocd
spec:
  project: argocd-cicd  
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true 
      allowEmpty: false 
  sources:
  # - chart: web-app
  - repoURL: 'git@github.com:mohamedalaaelsafy/ArgoCD-Helm-Project.git'
    targetRevision: HEAD
    path: charts/web-app/
    helm:
      releaseName: web-app
      valueFiles:
      - values.yaml
  # - chart: jenkins
  - repoURL: 'git@github.com:mohamedalaaelsafy/ArgoCD-Helm-Project.git'
    targetRevision: HEAD
    path: charts/jenkins/
    helm:
      releaseName: jenkins
      valueFiles:
      - values.yaml


