
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  repositories: |
    - url:  git@github.com:mohamedalaaelsafy/ArgoCD-Helm-Project.git
      sshPrivateKeySecret:
        name: cicd-secret
        key: privateKey
timeout.reconciliation: 5s